### ISSUE TITLE
Criar método de importação de todas as escolas dado um estado através da API Educação Inteligente.

### ISSUE THREAD

**Issue by saviocamacam** [atlagroup/lacroix#18]
Usar o endereço http://educacao.dadosabertosbr.com/api como referencia para importação das informações das escolas de acordo ao model Escola do projeto, assim tendo que verificar as informações necessárias.

**Comment by hensou** [comment]
@saviocamacam ao invés de importar todas as escolas de um determinado estado não seria melhor se deixasse a API cuidar da busca e somente cadastrar as escolas necessárias? Isso pouparia recursos como banco de dados e banda, já que as requisições seriam feitas para a API e nosso banco não teria escolas cadastradas que não possuem nenhum aluno.

**Comment by saviocamacam** [comment]
@rickftime É verdade, mas e se a API cair ou sair do ar? É um projeto de ong e não confiável. Mesmo que a função não suba esses dados para a aplicação, queria mesmo esses dados em caráter de backup, porque não achei essas informações em nenhum outro site, nem no mec, pelo menos não à disposição de consulta organizada. A gente pode baixar todos os dados da API que são interessantes, como a lista de municípios e a lista de escolas e deixa-los guardados e fazer a consulta diretamente no na API.
